development:
  adapter: postgresql
  encoding: unicode
  database: issue_tracker_development
  host: localhost
  username: postgres
  password: 10051991fantaz1
  port: 5432
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: issue_tracker_test
  host: localhost
  username: postgres
  password: 10051991fantaz1
  port: 5432
  pool: 5
